### ISSUE TITLE
Unexpected color shifts when wavelet residual layer is disabled

### ISSUE THREAD

**Issue by assaft** [aferrero2707/PhotoFlow#115]
Photoflow 0.2.7 (patched as described in Issue #113) on Windows 10.

I played with the new wavelet decomposition preset and applied it to my development. Once I disabled the residual layer I got this:
![wavelet](https://cloud.githubusercontent.com/assets/4903680/19432380/0ca06106-9465-11e6-88b0-9c81c34966c8.png)

[ORF file](https://dl.dropboxusercontent.com/u/21642925/P9040307.ORF)
[PFI file
](https://dl.dropboxusercontent.com/u/21642925/P9040307-wavelet.pfi)

**Comment by aferrero2707** [comment]
This is normal: the residual layer (the one associated with the "split details" tool) is actually outputting several images at once, one for the residual + one for each detail level. The clone layers inside the "scale 1/2/3/45" groups simply clone one of the output images of the "split details" layer, which is then blended back in "grain merge" mode.

If you hide the "split details" layer, you also disable the input of the clone layers in the "scale 1/2/3/45" groups, with unpredictable results.

In order to use the various detail levels for image sharpening, what you need to do is to add a clone of the original image just above the "split details" layer: this way, the various "grain merge" blends will be applied to the original image and not the residual one.

**Comment by aferrero2707** [comment]
Fixed by commit https://github.com/aferrero2707/PhotoFlow/commit/0641fb091fbe42e2a119166e5365f0088849ae48
 in stable branch, which adds the possibility of outputting the original image instead of the wavelets residual from the "split details" tool.
