### ISSUE TITLE
Not able to compile under Arch Linux

### ISSUE THREAD

**Issue by tuxflo** [aferrero2707/PhotoFlow#13]
The build script ./build_all.sh stopps with the error:
```
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/tmp/PhotoFlow/build/VIPS/libvips/cplusplus'
make[2]: Leaving directory '/tmp/PhotoFlow/build/VIPS/libvips/cplusplus'
make[1]: Leaving directory '/tmp/PhotoFlow/build/VIPS/libvips/cplusplus'
Making install in python
make[1]: Entering directory '/tmp/PhotoFlow/build/VIPS/libvips/python'
for f in Vips.py ; do \
    [ -e ./$f ] || ln -s ./$f ./$f; \
done
make[2]: Entering directory '/tmp/PhotoFlow/build/VIPS/libvips/python'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/gi/overrides'
/usr/bin/mkdir: cannot create directory ‘/gi’: Permission denied
Makefile:432: recipe for target 'install-vips_overridesPYTHON' failed
make[2]: *** [install-vips_overridesPYTHON] Error 1
make[2]: Leaving directory '/tmp/PhotoFlow/build/VIPS/libvips/python'
Makefile:530: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/tmp/PhotoFlow/build/VIPS/libvips/python'
Makefile:625: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
VIPS compilation failed
./build_all.sh  84.50s user 5.73s system 58% cpu 2:34.65 total
```
Is it right that the compile process wants to create a folder at /gi not at .../LIBVIPS_DIRECTORY/gi?
Also it would be good, to add a check to the build script, that checks if there is already the libvips repo, and if so just doing a git pull. When I tried to figure out what is wrong with the build script it always did the git clone again which took some time.

**Comment by aferrero2707** [comment]
The issue seems to be related to the pyvips8 bindings, which are not enabled by the configure script on my system... could you try to refresh your repository and run the script again, and report if it works? I've added

--enable-pyvips8=no 

to the configure parameters, since Python bindings are anyhow not needed to compile photoflow.

I've also included your suggestion of simply pulling the updated sources if the libvips directory already exists.

**Comment by tuxflo** [comment]
Ok I think the Python bindings are not a problem anymore, but the build now fails with
```
Linking CXX executable pfbatch
/usr/bin/ld: /tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(package.o): undefined reference to symbol 'g_module_symbol'
/usr/lib/libgmodule-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/CMakeFiles/pfbatch.dir/build.make:100: recipe for target 'src/pfbatch' failed
make[2]: *** [src/pfbatch] Error 1
CMakeFiles/Makefile2:120: recipe for target 'src/CMakeFiles/pfbatch.dir/all' failed
make[1]: *** [src/CMakeFiles/pfbatch.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

But thanks for the quick response and fix!

**Comment by aferrero2707** [comment]
Oooops! It seems that your system is stricter than mine when linking the static vips library... I've explicitly added  the GLib libraries to the linker command, which should fix the "undefined reference" issues.

**Comment by tuxflo** [comment]
I did a git pull but there are still more compiling issues :( but thanks a lot for helping. If I can manage to compile it, I can create an package in the Arch Linux User Repository.
Here are the errors:
```
/tmp/PhotoFlow/src/base/blend_vivid_light.hh:76:2: warning: #warning "TODO: handle vivid light blend for Lab and CMYK" [-Wcpp]
 #warning "TODO: handle vivid light blend for Lab and CMYK"
  ^
Linking CXX executable pfbatch
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(init.o): In function `vips_shutdown':
init.c:(.text+0x3ed): undefined reference to `gsf_shutdown'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(init.o): In function `vips_init':
init.c:(.text+0x8e3): undefined reference to `gsf_init'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(webp2vips.o): In function `read_free':
webp2vips.c:(.text+0x11): undefined reference to `WebPIDelete'
webp2vips.c:(.text+0x25): undefined reference to `WebPFreeDecBuffer'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(webp2vips.o): In function `read_new':
webp2vips.c:(.text+0x149): undefined reference to `WebPInitDecoderConfigInternal'
webp2vips.c:(.text+0x15f): undefined reference to `WebPGetFeaturesInternal'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(webp2vips.o): In function `read_image':
webp2vips.c:(.text+0x262): undefined reference to `WebPDecodeRGBAInto'
webp2vips.c:(.text+0x268): undefined reference to `WebPDecodeRGBInto'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(webp2vips.o): In function `vips__iswebp_buffer':
webp2vips.c:(.text+0x32e): undefined reference to `WebPGetInfo'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(webp2vips.o): In function `vips(int, short, wchar_t,...)(bool,  *)':
webp2vips.c:(.text+0x362): undefined reference to `WebPGetInfo'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(dzsave.o): In function `vips_gsf_path':
dzsave.c:(.text+0xbd1): undefined reference to `gsf_outfile_new_child'
dzsave.c:(.text+0xc27): undefined reference to `gsf_outfile_new_child'
dzsave.c:(.text+0xc66): undefined reference to `gsf_outfile_new_child_full'
dzsave.c:(.text+0xc83): undefined reference to `gsf_outfile_new_child_full'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(dzsave.o): In function `strip_work':
dzsave.c:(.text+0xfc6): undefined reference to `gsf_output_write'
dzsave.c:(.text+0xfdd): undefined reference to `gsf_output_close'
dzsave.c:(.text+0x110f): undefined reference to `gsf_output_error'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(dzsave.o): In function `vips_gsf_tree_close':
dzsave.c:(.text+0x36f0): undefined reference to `gsf_output_is_closed'
dzsave.c:(.text+0x3702): undefined reference to `gsf_output_is_closed'
dzsave.c:(.text+0x370f): undefined reference to `gsf_output_close'
dzsave.c:(.text+0x3745): undefined reference to `gsf_output_close'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(dzsave.o): In function `vips_foreign_save_dz_build':
dzsave.c:(.text+0x3984): undefined reference to `gsf_output_stdio_new'
dzsave.c:(.text+0x39a0): undefined reference to `gsf_outfile_zip_new'
dzsave.c:(.text+0x39d5): undefined reference to `gsf_outfile_new_child_full'
dzsave.c:(.text+0x3b85): undefined reference to `gsf_output_write'
dzsave.c:(.text+0x3b8d): undefined reference to `gsf_output_close'
dzsave.c:(.text+0x3d10): undefined reference to `gsf_output_write'
dzsave.c:(.text+0x3d18): undefined reference to `gsf_output_close'
dzsave.c:(.text+0x3ecc): undefined reference to `gsf_outfile_stdio_new'
dzsave.c:(.text+0x3fbf): undefined reference to `gsf_output_printf'
dzsave.c:(.text+0x3fce): undefined reference to `gsf_output_printf'
dzsave.c:(.text+0x3fe5): undefined reference to `gsf_output_printf'
dzsave.c:(.text+0x3ffa): undefined reference to `gsf_output_printf'
dzsave.c:(.text+0x400f): undefined reference to `gsf_output_printf'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(dzsave.o):dzsave.c:(.text+0x401e): more undefined references to `gsf_output_printf' follow
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(dzsave.o): In function `vips_foreign_save_dz_build':
dzsave.c:(.text+0x4085): undefined reference to `gsf_output_close'
dzsave.c:(.text+0x40de): undefined reference to `gsf_output_printf'
dzsave.c:(.text+0x40e6): undefined reference to `gsf_output_close'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(dzsave.o): In function `vips_gsf_tree_free':
dzsave.c:(.text+0x4392): undefined reference to `gsf_output_is_closed'
dzsave.c:(.text+0x43ad): undefined reference to `gsf_output_is_closed'
dzsave.c:(.text+0x43d5): undefined reference to `gsf_output_close'
dzsave.c:(.text+0x43e5): undefined reference to `gsf_output_close'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(vips2webp.o): In function `vips__webp_write_file':
vips2webp.c:(.text+0x37): undefined reference to `WebPEncodeRGBA'
vips2webp.c:(.text+0x3c): undefined reference to `WebPEncodeRGB'
vips2webp.c:(.text+0xd4): undefined reference to `WebPEncodeLosslessRGB'
vips2webp.c:(.text+0xd9): undefined reference to `WebPEncodeLosslessRGBA'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(vips2webp.o): In function `vips__webp_write_buffer':
vips2webp.c:(.text+0x197): undefined reference to `WebPEncodeRGB'
vips2webp.c:(.text+0x19d): undefined reference to `WebPEncodeRGBA'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `vips_fits_error':
fits.c:(.text+0x8): undefined reference to `ffgerr'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `vips_fits_new_read':
fits.c:(.text+0xd3): undefined reference to `ffopentest'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `vips_fits_close':
fits.c:(.text+0x179): undefined reference to `ffclos'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `vips_fits_get_header':
fits.c:(.text+0x20c): undefined reference to `ffgiprll'
fits.c:(.text+0x35f): undefined reference to `ffghsp'
fits.c:(.text+0x3d1): undefined reference to `ffgrec'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `fits2vips_generate':
fits.c:(.text+0x65c): undefined reference to `ffgsv'
fits.c:(.text+0x7d1): undefined reference to `ffgsv'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `vips_fits_write':
fits.c:(.text+0xa0a): undefined reference to `ffppx'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `vips_fits_write_meta':
fits.c:(.text+0xae9): undefined reference to `ffprec'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `vips__fits_isfits':
fits.c:(.text+0xccc): undefined reference to `ffiopn'
fits.c:(.text+0xce1): undefined reference to `ffclos'
/tmp/PhotoFlow/build/VIPS/build/lib/libvips.a(lt1-fits.o): In function `vips__fits_write':
fits.c:(.text+0xe07): undefined reference to `ffinit'
fits.c:(.text+0xed4): undefined reference to `ffcrimll'
collect2: error: ld returned 1 exit status
src/CMakeFiles/pfbatch.dir/build.make:100: recipe for target 'src/pfbatch' failed
make[2]: *** [src/pfbatch] Error 1
CMakeFiles/Makefile2:120: recipe for target 'src/CMakeFiles/pfbatch.dir/all' failed
make[1]: *** [src/CMakeFiles/pfbatch.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by aferrero2707** [comment]
Uhmmm... then I would propose to take a different approach.

This build_all.sh script was actually a "dirty" hack to help compiling both photoflow and VIPS from their git repositories, since generally the official VIPS development packages are too old in most of the distros.

In order to do things properly, you need to:

* get VIPS from github, compile it and install it:
  cd your_sources_directory
  git clone https://github.com/jcupitt/libvips.git
  cd libvips
  ./bootstrap.sh
  export FLAGS="-O2 -msse4.2 -ffast-math -ftree-vectorize"
  export CFLAGS="$FLAGS" 
  export CXXFLAGS="$FLAGS -fpermissive"
  ./configure --prefix=/usr/local --disable-gtk-doc --disable-gtk-doc-html \
				--disable-introspection --enable-debug=no --without-python  --without-magick\
				--enable-pyvips8=no --enable-shared=yes --enable-static=no
  make
  sudo make install

* get and compile photoflow:
  cd your_sources_directory
  git clone https://github.com/aferrero2707/PhotoFlow.git
  cd PhotoFlow/build
  export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/Release -DINSTALL_PREFIX=$(pwd)/Release ../
  make install

This will create a photoflow executable:
  ./Release/bin/photoflow 
and a batch processor:
  ./Release/bin/pfbatch

You might need to add "/usr/local/lib" to your LD_LIBRARY_PATH in order to find the custom VIPS libraries (that's why I've opted for static linking in the build_all.sh script...).

If you could volunteer to create Arch packages I would be extremely glad! And I'll give you all the support I can to get the procedure running (we went through it for Ubuntu already, and now the packaging seems to run quite smoothly).
In this case, you will probably want to build a more general VIPS library, including python bindings, imagemagick support and documentation... and of course change the installation prefixes. But we can have a closer look to that when it will be time.

**Comment by tuxflo** [comment]
Ok build process is done but unfortuanetly my Raw files are looking like that:
![photoflow](https://cloud.githubusercontent.com/assets/2816893/5978544/babf9e8a-a8a0-11e4-952a-a32e3a51823a.png)

**Comment by aferrero2707** [comment]
This is "normal" (or at least "expected"): the module that opens raw files does not perform any post-processing, and the pixel data is still in bayer pattern format... this cannot be displayed correctly.

You need to add a "RAW developer" layer above the "RAW loader" to process the RAW data (white balance, demosaicing, exposure compensation, color conversion, etc...). For that, you need to:
* click on the small "+" button below the layers list
* select the "RAW" tab in the "New layer" dialog
* select the "RAW developer" tool (the only one in this tab for the moment)

At this point, a new layer should be added and the RAW development configuration dialog should be opened automatically, and the preview should finally show your image.

You will find a detailed tutorial about RAW image processing here: http://photoflowblog.blogspot.com/2014/09/tutorial-how-to-process-raw-image-in.html

and another one here: http://photoflowblog.blogspot.com/2014/12/color-spot-raw-white-balance-mode-in.html

The visualization of non-processed RAW files has definitely to be fixed, I agree... 

The advantage of having a separate tool for RAW development is that you can save your preferred settings as a preset, independently of the RAW file being actually processed. For that, you have to select the "RAW developer" layer and click on the "Save" button below the layers list. Then choose a meaningful file name with extension ".pfp": the current parameters of the "RAW develper" layer will be saved. Next time you will open a RAW file, instead of adding a "RAW developer" layer you could click on "Load" and choose the previously saved ".pfp" preset: this will create a "RAW developer" layer and set the parameters according to the values stored in the preset.

**Comment by tuxflo** [comment]
Ok now I can see the image and it is looking great. I think this issue can be closed now. Just a last question:
Which is the "proper" way to add /usr/local/lib to the LD_LIBRARY_PATH? Because when I create a package for the AUR I can not use export LD_LIBRARY_PATH because it would not remain after a reboot. Can I set the path of VIPS during configure?

Btw. I like having the Raw Developer as a separate modul, maybe someday someone can build a preset which maked the images look like exported with the Nikon Software. Like with the colors as you described [here](http://photoflowblog.blogspot.de/2014/09/tutorial-how-to-match-nikon-in-camera.html).
Is there a IRC channel for the Photoflow Editor?

**Comment by aferrero2707** [comment]
About your question: for an official package, I assume one has to install VIPS and PhotoFlow under /usr (and not /usr/local), so that there is no problem with paths. However, I do not really have experience with arch linux...

Concerning the colors, I can try to "guide" you through the process I've followed to match the Nikon colors for my D300 camera. However, for that you'll need a windows machine for running ViewNX, as described here: http://50.87.144.65/~rt/w/index.php?title=How_to_get_Nikon_ICM_profiles_from_NX2.
Once you have the proper ICM profile, my tutorial should should explain you how to use it in the RAW developer module. We can further discuss this point here, if you like.

No IRC channel yet, I don't even know if I would have the time to follow that...

**Comment by tuxflo** [comment]
I played arround with the color profiles and I really like it. The colors are exactly the same which is pretty nice. Now I can stop shooting Raw+Jpg because I get the same results just by adding a preset.
But during testing I found another Bug:
If you want to export an image and don't add an fileextension like .jpg to the filename, the application crashes with "core dumped":
```
(photoflow:12959): GLib-GObject-WARNING **: invalid uninstantiatable type '(null)' in cast to 'GObject'
**
ERROR:/home/flo/Programme_lokal/PhotoFlow/src/base/photoflow.cc:160:void PF::pf_object_unref(GObject*, const char*): assertion failed: (object->ref_count > 0)
[1]    12959 abort (core dumped)  build/Release/bin/photoflow
```

**Comment by aferrero2707** [comment]
I personally still shoot RAW+Jpeg, simply because Jpegs are very handful for quick browsing...
Anyway, I'm glad you succeeded to match the Nikon colors!

Concerning the crash, I'll modify the code so that wrong file names are properly handled and trigger a message dialog.

**Comment by inserttexthere** [comment]
I get this error:

In file included from /home/user/build/photoflow/PhotoFlow/src/operations/raw_output.cc:47:0:
/home/user/build/photoflow/PhotoFlow/src/operations/../dt/external/adobe_coeff.c: In function ‘void dt_dcraw_adobe_coeff(const char*, float (*)[12])’:
/home/user/build/photoflow/PhotoFlow/src/operations/../dt/external/adobe_coeff.c:534:3: error: narrowing conversion of ‘65535’ from ‘int’ to ‘short int’ inside { } [-Wnarrowing]
   };
   ^
/home/user/build/photoflow/PhotoFlow/src/operations/../dt/external/adobe_coeff.c:534:3: error: narrowing conversion of ‘65535’ from ‘int’ to ‘short int’ inside { } [-Wnarrowing]
/home/user/build/photoflow/PhotoFlow/src/operations/../dt/external/adobe_coeff.c:534:3: error: narrowing conversion of ‘65535’ from ‘int’ to ‘short int’ inside { } [-Wnarrowing]
/home/user/build/photoflow/PhotoFlow/src/operations/../dt/external/adobe_coeff.c:534:3: error: narrowing conversion of ‘65535’ from ‘int’ to ‘short int’ inside { } [-Wnarrowing]
/home/user/build/photoflow/PhotoFlow/src/operations/../dt/external/adobe_coeff.c:534:3: error: narrowing conversion of ‘65535’ from ‘int’ to ‘short int’ inside { } [-Wnarrowing]
src/CMakeFiles/pfbase.dir/build.make:836: recipe for target 'src/CMakeFiles/pfbase.dir/operations/raw_output.cc.o' failed
make[2]: *** [src/CMakeFiles/pfbase.dir/operations/raw_output.cc.o] Error 1
CMakeFiles/Makefile2:171: recipe for target 'src/CMakeFiles/pfbase.dir/all' failed
make[1]: *** [src/CMakeFiles/pfbase.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2

I am on linux manjaro xfce. Can someone help me with this?
Thanks!

**Comment by aferrero2707** [comment]
The easiest solution is to make this warning not fatal... I'll make a patch for that as soon as possible.

This part of code is directly inherited from darktable, and I prefer not to make modifications there that I would need to repeat every time I update the file from the darktable sources...

**Comment by aferrero2707** [comment]
This should be fixed in the next update of the master branch. I'll put a message here as soon as it will be available (probably in a couple of days).

**Comment by aferrero2707** [comment]
I've committed a fix to the master branch. Could you checkout the latest version and try to compile again? Let me know if the fix was enough.

Thanks!

**Comment by inserttexthere** [comment]
After some tweaks I got it working:
./configure --prefix=/usr/
and
export PKG_CONFIG_PATH="/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
and 
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/user/PhotoFlow -DINSTALL_PREFIX=/home/user/PhotoFlow ../
Don't know how correct/clean is this, but it works. I am new to linux.

**Comment by aferrero2707** [comment]
Was this after the fix I've committed? Did you use the build_all.sh script in the "build" subdirectory? This script should in principle take care of building and installing VIPS locally, if a recent enough version is not available from your distribution...

**Comment by inserttexthere** [comment]
Yes, this was after you committed the fix. I used instructions you provided in a post on jan. 29..

**Comment by aferrero2707** [comment]
Then I would say that the issue can be closed.

Only one minor suggestion: since you are compiling and installing VIPS from sources, I would suggest you to give /usr/local ans the installation prefix, nit to mix it with the official packages. 

Then you need to set the PKG_CONFIG_PATH accordingly before compiling photoflow:

    export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"

Hope this clarifies all your questions.
