### ISSUE TITLE
Display not complete

### ISSUE THREAD

**Issue by phweyland** [aferrero2707/PhotoFlow#146]
Ubuntu 16.10 - photoflow-git 30/05/2017

Opening this image with pfi, a part of this (vertical) image 
![image](https://cloud.githubusercontent.com/assets/23012047/26652653/df6ed05c-4650-11e7-9ed8-ce473f479665.png)

in 1:1 I can scroll vertically and horizontally without white zone.
Edit: If I move Raw Developper out of Basic, the image is fully shown.

**Comment by phweyland** [comment]
With crop inside Basic (the clear part of the image is the cropped part:
![image](https://cloud.githubusercontent.com/assets/23012047/26652883/a66d0f20-4651-11e7-8855-2041f03a1f81.png)

**Comment by aferrero2707** [comment]
If you put the crop layer above the RAW loader and below the RAW developer, what happens is that the RAW processing module only gets a portion of the RAW data, and likely gets confused.

If you put the crop layer inside a group, what happens is that the program tries to blend the cropped result of the processing in the group onto the original image. By default, what happens is that the sub-image resulting from the crop is overlayed with the output of the RAW developer and is put in the top-left corner.

To avoid this, set the blend mode of the "Basic" group to "passthrough".

Or even better, put the crop layer at the top of the layer stack. This has two advantanges:

* only the cropped image is automatically shown
* whatever mask or other element you add in your edit, it will not depend on the crop you apply, because it will be applied to the full image.

Suppose that in your edit you draw a mask with the path tool in some layer ABOVE the crop.
If you change the crop area for some reason, the path will likely be displaced and would need to be edited. However, if the crop layer is ABOVE the mask, this problem does not exist...

On the other hand, there is no performance drawback in having the cropping as the last operation, because in any case the portion of the image outside of the crop area will not be processed...

I hope this helps to understand what you are getting!

**Comment by phweyland** [comment]
Thanks for your explanation Carmelo. That clarifies the cropping behaviour.
If I set the blend mode to "passthrough" in case of the first image (no crop) that solves also the issue.
I have to improve my understanding of blending.
Is there a place where I can find a description of these modes ?

**Comment by aferrero2707** [comment]
@phweyland 
> Is there a place where I can find a description of these modes ?

Most of the blend modes used in PhotoFlow follow the GIMP and/or Photoshop conventions.
Here are few useful resources:
http://www.pegtop.net/delphi/articles/blendmodes/
http://photoblogstop.com/photoshop/photoshop-blend-modes-explained
https://docs.gimp.org/en/gimp-concepts-layer-modes.html
