### ISSUE TITLE
Horizontal/Vertical line tools

### ISSUE THREAD

**Issue by Fincer** [aferrero2707/PhotoFlow#168]
Thank you for this awesome editor! Few features still missing but otherwise Photoflow is quite good for daily photo processing.

One feature I still miss is a horizontal/vertical line tools similar to one included in Adobe Camera Raw editor (Hugin may have such tools, too). Have you considered adding these tools into Photoflow editor? I do a lot landscape photographing in which horizontal straightness matters quite much.

Basic concepts for a such tools would be as follows.

**Horizontal line tool, two possibilities:**
- A) Two user defined points which would present a straight line (by which the image would be rotated)
- B) Draw a line by dragging with a mouse, equal to Adobe Camera Raw's horizontal line tool

The current "rotate image with a slider" which can be found in Photoflow doesn't serve this purpose very well since the rotating step is too harsh for fine tuning. In addition, drawing a straight line is a vital visual reference.

**Vertical line tool:**
- A) Draw 2 vertical reference lines which would be used to transform image geometry, similar to Adobe Camera Raw's tool. Vertical lines would be useful for defining building corners photographed with wide-angle lenses, for example.

Otherwise, I find Photoflow quite useful already. Keep up the good work!

**Comment by aferrero2707** [comment]
Hi! Thanks for your suggestions!

What you propose for the image rotation tool is actually already existing, but was broken in recent versions of the code... now it is fixed in the stable branch. 

In order to initiate the mouse-assisted rotation, you have to select the scale/rotate layer and click twice in the preview to define the line that should end-up horizontal. Once the two points are defined, the image will be rotated and the line shown in the preview. At this point, the user has still the possibility to fine-tune the position of the two end points, and the rotation will be updated at each adjustment. The rotated image will be auto-cropped once the layer is de-selected.
Does this correspond to your idea?

Concerning the vertical lines tool, did you already had a look at the perspective correction tool? It allows to correct the image perspective by dragging the corners of what initially is a rectangle. The tool can be easily modified to include an option that only considers the vertical correction, discarding the horizontal one (or vice-versa). What do you think?

**Comment by Fincer** [comment]
Hi!

Sorry for bit delayed answer.

I should have taken a closer look on the tools already implemented in the program. Mouse-assisted rotation & perspective correction tool are exactly the features I was looking for! No more complaints or whatsoever! 

Thanks again!

**Comment by aferrero2707** [comment]
No need to apologise! The documentation is still almost completely lacking, so I'm not surprised you didn't find the proper tools. Anyway, I'm glad that you found what you were looking for, and do not hesitate to provide feedback and suggestions.
