### ISSUE TITLE
Preview window - proposition of improvements.

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#36]
1/ Remove scrollbars if image is fitted to window - more, remove scrollbars forever and allow catch image by left/middle click and move active view,
2/ Auto fit preview again to window if right panel appears.

**Comment by aferrero2707** [comment]
1/ Remove scrollbars if image is fitted to window -> good idea, scheduled for 0.2.1

Getting rid of scrollbars completely requires some thinking... I'm not sure that dragging with left/middle click is straightforward on machines like MacbookPro laptops. It requires some experimenting.

2/ Auto fit preview again to window if right panel appears -> also scheduled for 0.2.1
I would add: double-click on preview area to quickly switch between fit-to-screen and 1:1 zooming.

**Comment by aferrero2707** [comment]
Point 2/ is implemented and committed in stable branch.

Point 1/ is partly implemented and committed: scrollbars are removed when the imaged is fitted to the window, and a small dark border is added to better frame the image in the preview area.
However, scrollbars are still kept when the preview image is larger than the window. Their complete removal will be eventually included in later releases, since it involves changing the handling of mouse events in the preview area.

The modification will appear in the next 0.2.1 release. Closing issue for now.
