### ISSUE TITLE
Scale/Rotate - spin buttons don't work

### ISSUE THREAD

**Issue by salvadhor** [aferrero2707/PhotoFlow#37]
Rotate angle can't be changed with spin buttons - sometimes Photoflow hangs up but mostly there's no reaction. Slider works as usual.

**Comment by aferrero2707** [comment]
This was due to two overlapping issues:

1. the spin button value, when clicking on the up/down arrows, was incrementing by 0.001 steps, which was too precise; now it is set to 0.01
2. each change in the spin button value triggers an update of the preview image. Normally, for efficiency reasons the processing engine treats several incoming update requests as a single one. However, this doesn't seem to work in the specific case of the spin buttons, making the interface irresponsive.

I'll have to dig further on point 2.

**Comment by aferrero2707** [comment]
Fixed in stable branch.
