### ISSUE TITLE
Repo for fedora 22 is broken 

### ISSUE THREAD

**Issue by chazzbg** [aferrero2707/PhotoFlow#43]
This is the error when added the fedora 22 repo info
> Failed to synchronize cache for repo 'oleastre-PhotoFlow' from 'https://copr-be.cloud.fedoraproject.org/results/oleastre/PhotoFlow/fedora-22-x86_64/': Cannot download repomd.xml: > Cannot download repodata/repomd.xml: All mirrors were tried, disabling.

fedora 21 repo works, but it fails to install due to unmet dependencies for libHalf

**Comment by aferrero2707** [comment]
The Fedora packages are still at version 0.1.6, so quite outdated... I think that the best option for you at the moment is to compile from sources (see instructions here: http://aferrero2707.github.io/PhotoFlow/install.html#downloading-and-compiling), at least until I clarify the situation concerning Fedora packaging.

**Comment by chazzbg** [comment]
Thanks for the information!

**Comment by oleastre** [comment]
After a lot of other priorities, I did not took the time to update the package.
I'm trying to get it build right now. Will let you know when it's done.

**Comment by aferrero2707** [comment]
Thanks!

**Comment by chazzbg** [comment]
It's not big of a deal, take your time. 
Just wanted to report that :)

**Comment by oleastre** [comment]
Got it compiling on my computer (and build submitted to copr); but I had to patch the current master code to get it compiling with gcc5 and gtkmm3.
So, you have pending pull requests :)

**Comment by aferrero2707** [comment]
I had to revert part of your pull request, because the darktable code you have included is using a new camera naming scheme (which is not used in 1.6.9, but only in the git development version).

Could you tell me what exactly was the problem under gcc5?

On the other hand, I have included your patch for gtkmm3 (thanks!) and done some more work on gtk3 compatibility. The GTK3 version will probably become fully operational in the next few days, apart from a still ugly theme...

**Comment by oleastre** [comment]
Good news for the GTK3 version. Thanks a lot.
For the gcc5 (c++11)  problem, it's a little bit more strict about integer conversion and it errors with
```error: narrowing conversion of '65535' from 'int' to 'short int'```
In adobe_coeff there are some places in the table where they try to put 0xffff in a signed short which fails.
This can be solved by changing the structure definition (for values that are never used) with the following patch:
```patch
diff --git a/src/dt/external/adobe_coeff.c b/src/dt/external/adobe_coeff.c
index 1863142..baa9ec8 100644
--- a/src/dt/external/adobe_coeff.c
+++ b/src/dt/external/adobe_coeff.c
@@ -13,7 +13,8 @@ static void dt_dcraw_adobe_coeff(const char *name, float cam_xyz[1][12])
 {
   static const struct {
     const char *prefix;
-    short black, maximum, trans[12];
+    int black, maximum;
+    short trans[12];
   } table[] = {
     { "AGFAPHOTO DC-833m", 0, 0, { 11438,-3762,-1115,-2409,9914,2497,-1227,2295,5300 } }, /* DJC */
     { "Apple QuickTake", 0, 0, { 21392,-5653,-3353,2406,8010,-415,7166,1427,2078 } },  /* DJC */
```

Or see my branch at https://github.com/oleastre/PhotoFlow/tree/compile-with-gcc5 (can do a PR if needed)

**Comment by aferrero2707** [comment]
I've pushed your fix to the master and stable branches. It doesn't seem to have any bad side effect.

I'll keep this issue open until you can confirm that Fedora packages work properly.

Thanks!

**Comment by oleastre** [comment]
For info, here is the darktable diff that completely removed the black and maximum fields, as those are not used.
http://redmine.darktable.org/projects/darktable/repository/revisions/800376419f424497d5a8cf319e4ec629725b3b5e

I'm waiting for fedora copr to finish the build and let you know the result.

**Comment by aferrero2707** [comment]
The problem is that in the Darktable development version they also changed the naming scheme for the cameras, and my code is not yet ready for that... I think it can be done for next release.

In 1.6.9 they still use the old naming scheme and the black and maximum fields are still there.
Your fix does not introduce any risk of "bad side effects", so I would leave things like that until I had the possibility to test in detail the new adobe coefficients version.

**Comment by oleastre** [comment]
The copr build succeeded and seems to work.

**Comment by aferrero2707** [comment]
Great!

I've added the install instructions in the release page, and I'll put a post on G+ to announce the availability of the Fedora packages.

Maybe it would be good to update the project description in the copr with the current README.md, since there are some features (like printing and plug-ins) that not planned anymore (at least not for the moment).

**Comment by oleastre** [comment]
Description is updated and new packages are in copr build queue :)

**Comment by oleastre** [comment]
Note, I will probably add fedora 23 builds in the coming week (in fact when I get my computer updated to it.)

**Comment by oleastre** [comment]
Forgot to tell you: do not hesitate to ping me when a new version is about to be released. 
I will prepare verify it still works with the latest fedora version and prepare new packages :)

**Comment by aferrero2707** [comment]
Thanks, that's really great! I usually send a message to package
maintainers whenever the master branch receives a new stable version, and
then I wait for packages to be ready before announcing the new version on
blog and social media...

You can also eventually subscribe to GitHub RSS feeds to get notifications
about the activity in the PhotoFlow repository.

Best,
Andrea
