### ISSUE TITLE
Spot and Color Spot WB freeze the app (was: Can't open CR2 files (Canon RAW) and DNG files)

### ISSUE THREAD

**Issue by NeverWise** [aferrero2707/PhotoFlow#44]
Great software but as I have already write in the title I can't open file CR2 and DNG.
They are shown with a grey noise...

**Comment by aferrero2707** [comment]
This is most likely due to the fact that no "RAW developer" layer is added on top of the opened RAW file (see this blog post for more details: http://photoflowblog.blogspot.fr/2014/09/tutorial-how-to-process-raw-image-in.html).

PhotoFlow splits the actions of loading a RAW file and actually converting it into an RGB image into separate steps, each assigned to a separate tool: the "RAW loader" simply decodes the RAW data into a 1-channel image, and the "RAW developer" applies all development steps like white balance, exposure compensation, demosaicing and output color conversion to a working RGB colorspace.

Thais allows to save the RAW processing parameters as a preset that can be quickly reloaded or used in batch processing, and independently of the actual RAW file being processed.

The output of the "RAW loader" tool should appear as a dark grayscale image, showing the unprocessed linear bayer pattern data, however due to a bug in the current version the preview shows garbage (this will be fixed for next version). This does not fortunately prevent from having the correct output once the "RAW developer" layer is added.

**Comment by NeverWise** [comment]
Thanks for the information! I read some tutorial of the site http://photoflowblog.blogspot.fr but I have a trouble with WB. I try to click on the image with SPOT WB or COLOR SPOT WB selected but nothing happen. Where I'm wrong?

**Comment by aferrero2707** [comment]
Those old tutorials might be quite outdated... I'm writing a new documentation page in the wiki, but it's not yet finished: https://github.com/aferrero2707/PhotoFlow/wiki/RAW-images-processing.

However, I have just realized that the SPOT WB and COLOR SPOT WB are broken in the current version, so that they are unusable (they freeze the app). I'll fix that for next release and meanwhile provide an updated documentation.

**Comment by NeverWise** [comment]
Ok thanks, I look forward to the next version. Meanwhile if you want I can change the title of this issue in "white balance freeze the app"? (also you can do it ;-))

**Comment by aferrero2707** [comment]
Fixed in current stable branch, will appear in upcoming version 0.2.3
